
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer
# pyinstaller --onefile --add-data "assets;assets" --add-data "АТП_актШаблон.docx;." gui.py


from datetime import datetime
from pathlib import Path
from functools import partial
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from akt_montazha import *
import requests

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")

print("id 1_3")
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("862x480")
window.configure(bg = "#3A7FF6")


canvas = Canvas(
    window,
    bg = "#3A7FF6",
    height = 442,
    width = 862,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    88.0,
    70.0,
    anchor="nw",
    text="Формирование Акта монтажа",
    fill="#FCFCFC",
    font=("Roboto Bold", 24 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    653.0,
    241.0,
    image=image_image_1
)


def update_canvas_text(folder_path):
    canvas.delete("folder_text") 
    canvas.create_text(
        113.0, 
        422.0,
        anchor="nw",
        text=f"Выбранная папка: {folder_path}",
        fill="#FFFFFF",
        font=("Inter Bold", 13 * -1),
        tags="folder_text" 
    )


# canvas.create_text(
#     431.0,
#     98.0,
#     anchor="nw",
#     text="by Gekata",
#     fill="#FFFFFF",
#     font=("Inter Light", 12 * -1)
# )
selected_files: list[str] = []
selected_files_otv: list[str] = []

button_image_1 = PhotoImage(
    file=relative_to_assets("button_vybrat-fajly.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: selecting_some_files(),
    relief="flat"
)
button_1.place(
    x=88.0,
    y=147.0,
    width=247.0,
    height=55.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_vybrat-otvetnye.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: selecting_some_otv_files(),
    relief="flat"
)
button_2.place(
    x=88.0,
    y=231.0,
    width=250.0,
    height=55.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_nachat-obrabotku.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: start_handle(),
    relief="flat"
)


button_3.place(
    x=88.0,
    y=315.0,
    width=245.0,
    height=55.0
)
button_image_4 = PhotoImage(
    file=relative_to_assets("button_dobavit-kody.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: fill_dictionary(),
    relief="flat"
)


button_4.place(
    x=88.0,
    y=395.0,
    width=245.0,
    height=55.0
)
def send_report(text=None, process=None, responsible=None):

    requests.post(f"https://script.google.com/macros/s/AKfycbzDwjE6Pu1a7otho2EHwbI-4yNoEmLijTfwWfI3toWpDpJ6rc-O1pKljV6XMLJmQIyJ/exec?time={datetime.now().strftime('%d.%m.%Y %H:%M:%S')}&process={process}&responsible={responsible}&text={text}")

send_report(text="",process="Akt Montazha", responsible=os.getlogin())

window.resizable(False, False)
window.mainloop()
